[tool.poetry]
name = "shelter"
version = "0.1.0"
description = ""
authors = ["Damián Silvani <munshkr@gmail.com>"]

[tool.poetry.dependencies]
python = "*"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
